### ISSUE TITLE
**New Maintainer Needed**

### ISSUE THREAD

**Issue by claviska** [yasirmturk/simple-php-captcha#29]
This was a fun project while it lasted, but I no longer have time to commit to maintaining it. If you're up for adopting it, please let me know below.

**Comment by gitodd** [comment]
Hi clavicle:

We have been using php captcha on our non-profit website and it's been a really helpful captcha. Recently, we have switched servers to one running Mac OS Sierra and the  aptcha script has stopped loading the image created. When I copy the same files to my laptop running Mamp it works fine. I think the problem lies in the Apple's System Integrity Protection interferring with the captcha code on the OSX Sierra server. I tried to go to phpcaptcha.org for help but the website can't be reached. Sorry for sending this question to you here but I thought your might be aware of potential incompatibilities with Mac OSX Sierra.
Any insights would be much appreciated.

Thanks.

Todd

**Comment by gitodd** [comment]
Apologies on the autocorrected greeting. :-)

**Comment by yasirmturk** [comment]
yeah sure.. do u have any todo list as well?

**Comment by claviska** [comment]
Awesome. Just need to address the two PRs and whatever open issues still may be there. The rest is really up to you. I'll send a request.

**Comment by claviska** [comment]
Looks like you need to rename your fork (or delete it) before I can transfer.

**Comment by yasirmturk** [comment]
i have deleted mine

**Comment by claviska** [comment]
Sent!

**Comment by yasirmturk** [comment]
got it thanks.. plz share suggestions if there comes any to you :)
